### ISSUE TITLE
Plugin failed on kafka_2.11

### ISSUE THREAD

**Issue by superwhykz** [be-hase/kafka-elasticsearch-metrics-reporter#1]
Hi, thanks for the plugin any chances to test plugin with kafka_2.11?

**Comment by be-hase** [comment]
Oh, this plugin failed ?
What is your kafka version?

**Comment by superwhykz** [comment]
kafka 0.10.0.1 but uses scala 2.11.

https://kafka.apache.org/downloads.html

**Comment by be-hase** [comment]
What's kind of failed ?
I want to see a some error log.

**Comment by superwhykz** [comment]
It seems I am wrong. It does not relate to plugin. It is internal Kafka error.  Thanks man for a quick response! 

[2016-10-18 00:05:02,363] INFO Started KafkaElasticsearchMetricsReporter with polling period 10 seconds (com.behase.kafka.KafkaElasticsearchMetricsReporter)
[2016-10-18 00:05:02,431] FATAL  (kafka.Kafka$)
java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
    at kafka.api.ApiVersion$.<init>(ApiVersion.scala:46)
    at kafka.api.ApiVersion$.<clinit>(ApiVersion.scala)
    at kafka.server.Defaults$.<init>(KafkaConfig.scala:126)
    at kafka.server.Defaults$.<clinit>(KafkaConfig.scala)
    at kafka.log.Defaults$.<init>(LogConfig.scala:33)
    at kafka.log.Defaults$.<clinit>(LogConfig.scala)
    at kafka.log.LogConfig$.<init>(LogConfig.scala:152)
    at kafka.log.LogConfig$.<clinit>(LogConfig.scala)
    at kafka.server.KafkaConfig$.<init>(KafkaConfig.scala:265)
    at kafka.server.KafkaConfig$.<clinit>(KafkaConfig.scala)
    at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:28)
    at kafka.Kafka$.main(Kafka.scala:58)
    at kafka.Kafka.main(Kafka.scala)

**Comment by be-hase** [comment]
Hmm... java.lang.NoSuchMethodError...

But recently I never try my plugin.
I try later.
For now, I will close this issue.
